services:
  - type: web
    name: rafin-bot-panel
    env: python
    region: singapore
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 8 --timeout 120 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production